---
title: "Housing price prediction"
author: "Joseph Juhn (jjuhn2),Olga Scrivner (olgas2), Hardik Naik (hardikn2),Marie Biscarrat (biscarr1)"
output:
  html_document: 
    fig_width: 10
    toc: yes
  pdf_document: default
urlcolor: cyan
---

***

## Team

- Joseph Juhn (jjuhn2)
- Olga Scrivner (olgas2)
- Hardik Naik (hardikn2)
- Marie Biscarrat (biscarr1)

## Title

A tentitive title for this Data Analysis Project is: 

*Housing price prediction*

## Research Statement


## Data


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(MASS)
library(ggplot2)
```

```{r}
house_data_raw = read.table("kc_house_data.csv", header = T, sep = ",")

house_data_raw = na.omit(house_data_raw)
house_data_base = house_data_raw

house_data_base$bathrooms = mapvalues(house_data_base$bathrooms, from = c(0.75, 1.25,  1.75, 2.25, 2.75, 3.25, 3.75, 4.25, 4.75, 5.25, 5.75, 6.25, 6.75, 7.75), to = c(0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7.5))

house_data_base$floors = mapvalues(house_data_base$floors, from = c(1.5, 2.5, 3.5), to = c(1, 2, 3))

house_data_base$bedrooms_comp = ifelse(house_data_base$bedrooms>6,"6 +", as.character(house_data_base$bedrooms)) 

house_data_base$bathrooms_comp = ifelse(house_data_base$bathrooms>3.5,"3.5 +", as.character(house_data_base$bathrooms)) 

house_data_base$age = ifelse(house_data_base$yr_renovated == 0, 2015 - house_data_base$yr_built, 2015 - house_data_base$yr_renovated)

house_data_base$bedrooms_comp = as.factor(house_data_base$bedrooms_comp)
house_data_base$bathrooms_comp = as.factor(house_data_base$bathrooms_comp)
house_data_base$floors = as.factor(house_data_base$floors)
house_data_base$view = as.factor(house_data_base$view)
house_data_base$waterfront = as.factor(house_data_base$waterfront)
house_data_base$condition = as.factor(house_data_base$condition)
house_data_base$grade = as.factor(house_data_base$grade)

# Remove the variables 
remove = c("id","date","zipcode")
house_data = house_data_base[ , !(names(house_data_base) %in% remove)]

house_idx = sample(nrow(house_data), 5000)
house_trn = house_data[-house_idx, ]
house_tst = house_data[house_idx, ]

calc_test_rmse = function(model,log=FALSE){
  predictions = ifelse(log, exp(predict(model, house_tst)), predict(model, house_tst))
  sqrt(mean((house_tst$price - predictions) ^ 2))
}

```

```{r}

```

```{r}
model_additive = lm(price ~ . -grade - bathrooms - bedrooms - yr_built - yr_renovated, data = house_trn)
summary(model_additive)

model_bic = step(model_additive,trace=0, k= log(length(resid(model_additive))))

summary(model_bic)
calc_test_rmse(model_bic)

```

```{r}
keep = c("bedrooms" , "sqft_living" , "floors" , "waterfront" , 
    "view" , "condition", "grade" , "yr_built" , "yr_renovated" , "lat" , 
    "long" , "sqft_living15" , "sqft_lot15")
house_data_numeric = house_data_raw
house_data_numeric = house_data_raw[ , (names(house_data_raw) %in% keep)]

#pairs(house_data_numeric)
cor(house_data_numeric)
```


```{r}

model_interactive = lm(price ~ lat + long +(sqft_living + floors + waterfront + view  + sqft_above +  sqft_living15 + sqft_lot15 + age)^2 + bedrooms_comp + bathrooms_comp + condition,data = house_trn)

summary(model_interactive)$adj.r.squared
# model_aic = step(model_interactive,trace=0)
model_aic = stepAIC(model_interactive, direction = "both",trace = FALSE)
calc_test_rmse(model_aic)

# summary(model_aic)
# model_bic = step(model_interactive,trace=0, k= log(length(resid(model_interactive))))
# summary(model_bic)
# calc_test_rmse(model_bic)

```


## Reference

